language: node_js
node_js:
  - '0.12'
services:
  - mongodb
script: "npm run-script test-travis"
before_script: "npm install lecle/managerservice lecle/logservice lecle/mongodbservice lecle/analyticsservice lecle/analyticsdbservice git://github.com/kangchals/cronservice.git && mkdir public && mkdir public/files && mkdir logs"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
